Repository szut-fa19d/nhs-d, pull requests merged in 2020-12, with the labels that each got.

#20 Linter Fixes
  src/main/java/controller/AllPatientController.java
  src/main/java/controller/AllTreatmentController.java
  src/main/java/controller/Main.java
  src/main/java/controller/NewTreatmentController.java
  src/main/java/controller/TreatmentController.java
  src/main/java/controller/TreatmentControllerCommon.java
  src/main/java/datastorage/ConnectionBuilder.java
  src/main/java/datastorage/DAOimp.java
  src/main/java/datastorage/PatientDAO.java
  src/main/java/datastorage/TreatmentDAO.java
  src/main/java/model/Patient.java
  src/main/java/model/Person.java
  src/main/java/model/Treatment.java
  src/main/java/utils/DateConverter.java
  src/main/resources/AllPatientView.fxml
Labels: backend & business logic, bug

#23 Javadoc
  pom.xml
  src/main/java/controller/AllPatientController.java
  src/main/java/controller/AllTreatmentController.java
  src/main/java/controller/CommmonListController.java
  src/main/java/controller/Main.java
  src/main/java/controller/NewTreatmentController.java
  src/main/java/controller/TreatmentController.java
  src/main/java/controller/TreatmentControllerCommon.java
  src/main/java/datastorage/ConnectionBuilder.java
  src/main/java/datastorage/DAO.java
  src/main/java/datastorage/DAOFactory.java
  src/main/java/datastorage/DAOimp.java
  src/main/java/datastorage/TreatmentDAO.java
  src/main/java/model/DatabaseEntry.java
  src/main/java/model/Patient.java
  src/main/java/model/Person.java
  src/main/java/model/Treatment.java
  src/main/java/utils/DateConverter.java
  src/main/java/utils/Memoize.java
  src/main/resources/AllPatientView.fxml
Labels: documentation

#25 Login
  db/nursingHomeDB.script
  src/main/java/controller/AddUserController.java
  src/main/java/controller/AllPatientController.java
  src/main/java/controller/AllTreatmentController.java
  src/main/java/controller/AllUserController.java
  src/main/java/controller/CommonListController.java
  src/main/java/controller/LoginController.java
  src/main/java/controller/Main.java
  src/main/java/controller/MainWindowController.java
  src/main/java/controller/UserController.java
  src/main/java/datastorage/DAOFactory.java
  src/main/java/datastorage/GroupDAO.java
  src/main/java/datastorage/TreatmentDAO.java
  src/main/java/datastorage/UserDAO.java
  src/main/java/model/Group.java
  src/main/java/model/User.java
  src/main/java/utils/PasswordHash.java
  src/main/resources/AddUserView.fxml
  src/main/resources/AllUserView.fxml
  src/main/resources/LoginView.fxml
  src/main/resources/MainWindowView.fxml
Labels: backend & business logic, bug, enhancement, user story, view

#29 Lock&unlock patient&treatment
  .gitignore
  db/nursingHomeDB.lck
  db/nursingHomeDB.script
  src/main/java/controller/AllPatientController.java
  src/main/java/controller/AllTreatmentController.java
  src/main/java/controller/NewTreatmentController.java
  src/main/java/datastorage/PatientDAO.java
  src/main/java/datastorage/TreatmentDAO.java
  src/main/java/model/Patient.java
  src/main/java/model/Treatment.java
  src/main/resources/AllPatientView.fxml
  src/main/resources/AllTreatmentView.fxml
Labels: user story
